@extends('layouts.app')
@section('title',$project->name)
@section('content')
<div class="project-hero mb-4"><div><a class="back-link" href="{{ route('home') }}"><i class="bi bi-arrow-left"></i> プロジェクト一覧</a><p class="eyebrow mt-3">PROJECT</p><h1>{{ $project->name }}</h1><p>{{ $project->description ?: '説明はまだありません。' }}</p></div><div class="hero-actions">
    <a class="btn btn-outline-primary" href="{{ route('wbs') }}"><i class="bi bi-bar-chart-steps"></i> WBSを開く</a>
    @can('update',$project)<a class="btn btn-light" href="{{ route('projects.edit',$project) }}"><i class="bi bi-gear"></i> 編集</a>@endcan
    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#taskModal"><i class="bi bi-plus-lg"></i> タスク作成</button>
</div></div>
<div class="project-info-grid mb-4"><div><span>期間</span><strong><i class="bi bi-calendar3"></i>{{ $project->start_date->format('Y/m/d') }} — {{ $project->end_date->format('Y/m/d') }}</strong></div><div><span>PM</span><strong>{{ $project->members->where('role','pm')->pluck('user.name')->join(' / ') ?: '未設定' }}</strong></div><div><span>進捗</span><strong>{{ $project->progress() }}%</strong></div><div><span>メンバー</span><strong>{{ $project->members->count() }}名</strong></div></div>
<div class="content-panel"><div class="panel-heading"><div><p class="eyebrow">TICKETS</p><h3>タスク一覧 <span>{{ $project->tasks->count() }}</span></h3></div><div class="d-flex gap-2">@can('inviteMember',$project)<button class="btn btn-sm btn-light" data-bs-toggle="modal" data-bs-target="#inviteModal"><i class="bi bi-person-plus"></i> 招待</button>@endcan<button class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#taskModal"><i class="bi bi-plus"></i> タスク</button></div></div>
<div class="table-responsive"><table class="table task-table align-middle"><thead><tr><th>チケット</th><th>担当者</th><th>期間</th><th>進捗</th><th>ステータス</th></tr></thead><tbody>
@forelse($project->tasks->sortBy(['sort_order','id']) as $task)<tr><td><a class="task-link" href="{{ route('tasks.show',[$project,$task]) }}"><span>#{{ $task->id }}</span>{{ $task->title }}</a></td><td>@if($task->assignee)<span class="avatar avatar-sm">{{ mb_substr($task->assignee->name,0,1) }}</span> {{ $task->assignee->name }}@else<span class="text-secondary">未割当</span>@endif</td><td>{{ $task->start_date->format('m/d') }} — {{ $task->end_date->format('m/d') }}</td><td style="min-width:120px"><div class="d-flex align-items-center gap-2"><div class="progress app-progress flex-grow-1"><div class="progress-bar" style="width:{{ $task->progress }}%"></div></div><small>{{ $task->progress }}%</small></div></td><td><span class="task-status status-{{ $task->status->value }}">{{ $task->status->label() }}</span></td></tr>
@empty<tr><td colspan="5"><div class="empty-table"><i class="bi bi-inboxes"></i><p>タスクはまだありません。</p><button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#taskModal">最初のタスクを作成</button></div></td></tr>@endforelse
</tbody></table></div></div>
@if($project->invitations->isNotEmpty())<div class="content-panel mt-4"><div class="panel-heading"><div><p class="eyebrow">PENDING INVITATIONS</p><h3>招待承認待ち <span>{{ $project->invitations->count() }}</span></h3></div></div><div class="table-responsive"><table class="table task-table align-middle"><thead><tr><th>メールアドレス</th><th>権限</th><th>有効期限</th><th>状態</th><th></th></tr></thead><tbody>@foreach($project->invitations as $invitation)<tr><td>{{ $invitation->email }}</td><td>{{ strtoupper($invitation->role) }}</td><td>{{ $invitation->expires_at->format('Y/m/d H:i') }}</td><td>{{ $invitation->revoked_at ? '取消済み' : ($invitation->expires_at->isPast() ? '期限切れ' : '送信済み') }}</td><td><div class="d-flex gap-1 justify-content-end"><form method="post" action="{{ route('projects.invitations.resend',[$project,$invitation]) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-light"><i class="bi bi-arrow-repeat"></i> 再送</button></form>@if(!$invitation->revoked_at)<form method="post" action="{{ route('projects.invitations.revoke',[$project,$invitation]) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">取消</button></form>@endif</div></td></tr>@endforeach</tbody></table></div></div>@endif

<div class="modal fade" id="taskModal" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="{{ route('tasks.store',$project) }}">@csrf<div class="modal-header"><div><p class="eyebrow">NEW TICKET</p><h4 class="modal-title">タスクを作成</h4></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
<div class="col-12"><label class="form-label">タスク名</label><input class="form-control" name="title" required></div><div class="col-12"><label class="form-label">説明</label><textarea class="form-control" name="description" rows="3"></textarea></div>
<div class="col-md-6"><label class="form-label">担当者</label><select class="form-select" name="assignee_id"><option value="">未割当</option>@foreach($project->members as $m)<option value="{{ $m->user_id }}">{{ $m->user->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">親タスク</label><select class="form-select" name="parent_id"><option value="">なし</option>@foreach($project->tasks as $candidate)<option value="{{ $candidate->id }}">{{ $candidate->title }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">開始日</label><input class="form-control" type="date" name="start_date" value="{{ now()->format('Y-m-d') }}" required></div><div class="col-md-4"><label class="form-label">終了日</label><input class="form-control" type="date" name="end_date" value="{{ now()->addWeek()->format('Y-m-d') }}" required></div><div class="col-md-4"><label class="form-label">進捗</label><div class="input-group"><input class="form-control" type="number" name="progress" min="0" max="100" value="0" required><span class="input-group-text">%</span></div></div>
<div class="col-md-6"><label class="form-label">ステータス</label><select class="form-select" name="status">@foreach(App\Enums\TaskStatus::cases() as $status)<option value="{{ $status->value }}">{{ $status->label() }}</option>@endforeach</select></div><input type="hidden" name="sort_order" value="{{ $project->tasks->count() }}">
</div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">キャンセル</button><button class="btn btn-primary">作成</button></div></form></div></div>

@can('inviteMember',$project)<div class="modal fade" id="inviteModal" tabindex="-1" aria-labelledby="inviteModalLabel"><div class="modal-dialog"><form class="modal-content" method="post" action="{{ route('projects.invitations.store',$project) }}">@csrf<div class="modal-header"><div><p class="eyebrow">INVITE MEMBER</p><h4 class="modal-title" id="inviteModalLabel">{{ $project->name }}へ招待</h4></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="閉じる"></button></div><div class="modal-body">@include('invitations._form', ['project' => $project])</div><div class="modal-footer"><button class="btn btn-primary"><i class="bi bi-send"></i> 招待メールを送信</button></div></form></div></div>@endcan
@can('delete',$project)<form method="post" action="{{ route('projects.destroy',$project) }}" class="mt-4 text-end" onsubmit="return confirm('プロジェクトを削除しますか？')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i> プロジェクトを削除</button></form>@endcan
@endsection
