@extends('layouts.app')
@section('title','WBS')
@section('main-class','wbs-page')
@section('content')
<div class="wbs-topbar"><div><p class="eyebrow">WORK BREAKDOWN STRUCTURE</p><h1>WBS / ガントチャート</h1></div><div class="wbs-view-actions"><div class="btn-group day-scroll-controls" role="group" aria-label="WBSの日付を1日単位で移動"><button class="btn btn-light" id="scrollPrevDay" type="button" title="WBSを1日巻き戻す"><i class="bi bi-chevron-left"></i> 1日戻る</button><button class="btn btn-light" id="scrollNextDay" type="button" title="WBSを1日進める">1日進む <i class="bi bi-chevron-right"></i></button></div><button class="btn btn-light" id="scrollToday" type="button"><i class="bi bi-calendar-event"></i> 今日へ</button>@can('create', App\Models\Project::class)<a class="btn btn-primary" href="{{ route('projects.create') }}"><i class="bi bi-plus-lg"></i> プロジェクト</a>@endcan</div></div>
<div class="wbs-toolbar" id="taskToolbar" aria-label="選択タスク操作"><div class="toolbar-empty"><i class="bi bi-cursor"></i> タスクを選択すると編集ツールが表示されます</div><div class="toolbar-controls d-none">
    <div class="selected-name"><small>選択中</small><strong id="selectedTaskName"></strong></div><div class="btn-group"><button class="btn btn-light" data-shift="start,-1" title="開始日を1日早める"><i class="bi bi-skip-start"></i></button><button class="btn btn-light" data-shift="start,1" title="開始日を1日遅らせる"><i class="bi bi-skip-end"></i></button></div>
    <label>開始 <input class="form-control form-control-sm" type="date" id="toolbarStart"></label><div class="btn-group"><button class="btn btn-light" data-shift="end,-1" title="終了日を1日早める"><i class="bi bi-skip-start-fill"></i></button><button class="btn btn-light" data-shift="end,1" title="終了日を1日遅らせる"><i class="bi bi-skip-end-fill"></i></button></div><label>終了 <input class="form-control form-control-sm" type="date" id="toolbarEnd"></label><label>進捗 <div class="input-group input-group-sm"><input class="form-control" type="number" id="toolbarProgress" min="0" max="100"><span class="input-group-text">%</span></div></label><button class="btn btn-sm btn-primary" id="toolbarSave"><i class="bi bi-cloud-arrow-up"></i> 保存</button>
</div></div>
<div class="wbs-legend"><span><i class="legend-completed"></i>完了</span><span><i class="legend-past"></i>過去</span><span><i class="legend-future"></i>今日以降</span><span><i class="legend-overdue"></i>期限超過</span><small><i class="bi bi-grip-vertical"></i> 黒いゲージ端をドラッグして進捗変更</small></div>

<div class="wbs-shell" id="wbsShell" style="--date-count:{{ $dates->count() }}">
    <div class="wbs-row wbs-header"><div class="wbs-info header-info"><div>タスク / 担当者</div><div>進捗</div><div>ステータス</div></div><div class="wbs-timeline date-header">@foreach($dates as $date)<div class="date-cell {{ $date->isToday() ? 'is-today' : '' }} {{ $date->isWeekend() ? 'is-weekend' : '' }}" data-date="{{ $date->format('Y-m-d') }}" @if($date->isToday()) aria-label="今日" @endif><span>{{ $date->format('n/j') }}</span><small>{{ ['日','月','火','水','木','金','土'][$date->dayOfWeek] }}</small>@if($date->isToday())<b>TODAY</b>@endif</div>@endforeach</div></div>
@forelse($projects as $project)
    <div class="wbs-row project-row" data-project-id="{{ $project->id }}"><div class="wbs-info project-info" data-project-context="{{ $project->id }}" data-project-url="{{ route('projects.show', $project) }}" data-delete-url="{{ route('projects.destroy', $project) }}"><button class="tree-toggle" data-project-toggle="{{ $project->id }}"><i class="bi bi-chevron-down"></i></button><i class="bi bi-folder2-open folder-icon"></i><a href="{{ route('projects.show',$project) }}">{{ $project->name }}</a><small>{{ $project->tasks->count() }} tasks</small></div><div class="wbs-timeline project-timeline">@foreach($dates as $date)<div class="grid-cell {{ $date->isToday() ? 'is-today' : '' }} {{ $date->isWeekend() ? 'is-weekend' : '' }}"></div>@endforeach</div></div>
    @php($tasksById = $project->tasks->keyBy('id'))
    @foreach($project->tasks as $task)
        @php($depth=0) @php($cursor=$task) @while($cursor->parent_id && $depth<6) @php($depth++) @php($cursor=$tasksById->get($cursor->parent_id)) @if(!$cursor) @break @endif @endwhile
        <div class="wbs-row task-row" data-task-id="{{ $task->id }}" data-project-id="{{ $project->id }}" data-parent-id="{{ $task->parent_id }}" data-title="{{ $task->title }}" data-start="{{ $task->start_date->format('Y-m-d') }}" data-end="{{ $task->end_date->format('Y-m-d') }}" data-progress="{{ $task->progress }}" data-lock-version="{{ $task->lock_version }}" data-update-url="{{ route('tasks.update',[$project,$task]) }}">
            <div class="wbs-info task-info" style="--depth:{{ $depth }}"><div class="task-main">@if($task->children->isNotEmpty())<button class="tree-toggle" data-task-toggle="{{ $task->id }}"><i class="bi bi-chevron-down"></i></button>@else<span class="tree-spacer"></span>@endif<i class="bi {{ $task->status === App\Enums\TaskStatus::Completed ? 'bi-check-circle-fill text-info' : 'bi-check2-square' }}"></i><a href="{{ route('tasks.show',[$project,$task]) }}">{{ $task->title }}</a><select class="form-select form-select-sm wbs-assignee" aria-label="担当者"><option value="">未割当</option>@foreach($project->members as $membership)<option value="{{ $membership->user_id }}" @selected($task->assignee_id===$membership->user_id)>{{ $membership->user->name }}</option>@endforeach</select></div><div class="task-percent"><strong>{{ $task->progress }}%</strong></div><div><select class="form-select form-select-sm wbs-status" aria-label="ステータス">@foreach($statuses as $status)<option value="{{ $status->value }}" @selected($task->status===$status)>{{ $status->label() }}</option>@endforeach</select></div></div>
            <div class="wbs-timeline task-timeline">@foreach($dates as $date)@php($inRange=$date->betweenIncluded($task->start_date,$task->end_date)) @php($overdue=$task->status!==App\Enums\TaskStatus::Completed && $date->gt($task->end_date) && $date->lte(now()->startOfDay()))<div class="grid-cell {{ $date->isToday() ? 'is-today' : '' }} {{ $date->isWeekend() ? 'is-weekend' : '' }} @if($inRange) {{ $task->status===App\Enums\TaskStatus::Completed ? 'bar-completed' : ($date->lt(now()->startOfDay()) ? 'bar-past' : 'bar-future') }} @elseif($overdue) bar-overdue @endif"></div>@endforeach
            @php($startIndex=$dates->search(fn($d)=>$d->isSameDay($task->start_date))) @php($duration=$task->start_date->diffInDays($task->end_date)+1)
            @if($startIndex!==false)<div class="progress-gauge" style="--start:{{ $startIndex }};--days:{{ $duration }};--progress:{{ $task->progress }}" title="進捗 {{ $task->progress }}%"><div class="gauge-line"></div><button class="gauge-handle" aria-label="進捗をドラッグして変更"></button><span>{{ $task->progress }}%</span></div>@endif
            </div>
        </div>
    @endforeach
@empty<div class="empty-state m-5"><div class="empty-icon"><i class="bi bi-bar-chart-steps"></i></div><h3>表示できるプロジェクトがありません</h3></div>@endforelse
</div>
<div class="context-menu d-none" id="projectContext"><button data-action="open"><i class="bi bi-box-arrow-up-right"></i> プロジェクトを開く</button><button data-action="task"><i class="bi bi-plus-square"></i> タスク追加</button><button data-action="invite"><i class="bi bi-person-plus"></i> メンバー招待</button><hr><button class="text-danger" data-action="delete"><i class="bi bi-trash"></i> プロジェクト削除</button></div>
@endsection
